/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fc93a03c-a885-4414-8eef-93a801e0545e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Lm0z7VMH4",
    "aws_user_pools_web_client_id": "2oh9jcfq1a5vuks51nvi4qubfc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jszhh73aaffoziqargrahztbw4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
